### PR TITLE
Remove TODO section in the README

### PR DESCRIPTION
**Pull request by strugee**
These should probably be stored in GitHub Issues instead - I'd be happy to go add all these to the issue tracker should this get merged.

### CODE REVIEW

**Comment by davidbalbert** [comment]
@strugee my apologies for never merging this. I just merged a rewrite of Proxy that included a rewrite of the README, and I've taken the TODO section out.

No need to make issues. I don't think any of the TODOs are relevant any more.

**Comment by strugee** [comment]
Hah, no worries - I didn't remember I sent this even when I saw notifications about the rewrite!

**Comment by davidbalbert** [comment]
Thanks for understanding! Hope you're doing well :)

**Comment by strugee** [comment]
Of course, you too! I'm in NYC now so hopefully I'll see you in the space soon :-)

**Pull request closed without merging**
